### PR TITLE
allow to work with pest 3 also

### PR DESCRIPTION
**Pull request by mihaileu**

### CODE REVIEW

**Comment by wilsenhc** [comment]
Getting this merged would be awesome, to have support for Pest 3 🚀

**Comment by mberneis** [comment]
I am using this plugin as well - pls make pest3 compatible

**Comment by mihaileu** [comment]
@freekmurze could you please take a look

**Comment by lloricode** [comment]
you can use this PR while waiting

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/mihaileu/pest-plugin-test-time"
        }
    ],

    "require-dev": {
        "spatie/pest-plugin-test-time": "dev-feature/allow_pest3",
```

then `composer u`

**Comment by riasvdv** [comment]
Thanks!

**Pull request merged**
